### ISSUE TITLE
DoAll.ps1 fails on ARM64 host

### ISSUE THREAD

**Issue by timsneath** [microsoft/win32metadata#1305]
Probably relatively fixable? Here's the error:

```
Unhandled exception: System.BadImageFormatException: An attempt was made to load a program with an incorrect format. (0x8007000B)
   at ClangSharp.Interop.clang.getClangVersion()
   at ClangSharp.PInvokeGenerator..ctor(PInvokeGeneratorConfiguration config, Func`2 outputStreamFactory) in /_/sources/ClangSharp.PInvokeGenerator/PInvokeGenerator.cs:line 75
   at ClangSharp.Program.Run(InvocationContext context) in /_/sources/ClangSharpPInvokeGenerator/Program.cs:line 653
   at System.CommandLine.Handler.<>c__DisplayClass1_0`1.<SetHandler>b__0(InvocationContext context)
   at System.CommandLine.Invocation.AnonymousCommandHandler.<>c__DisplayClass2_0.<.ctor>g__Handle|0(InvocationContext context)
   at System.CommandLine.Invocation.AnonymousCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass18_0.<<UseParseErrorReporting>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass13_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass20_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__19_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass17_0.<<UseParseDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__6_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass9_0.<<UseExceptionHandler>b__0>d.MoveNext()
```

**Comment by riverar** [comment]
Can you clarify what ARM64 host we're talking here? Is this a Parallel's Windows on ARM machine? Or a native Windows on ARM machine? Or other?

**Comment by timsneath** [comment]
An astute question :) 

This is indeed a Windows 11 retail image (22000) running on Parallels atop a MacBook Air M2 running macOS Monterey.

**Comment by riverar** [comment]
@timsneath If you install the dotnet 6/7 x64 SDK, you need to edit your `PATH` and ensure the dotnet path points to `C:\Program Files\dotnet\x64` (not the default). This will ensure you're not using an arm64 SDK on the box and cause the above failures.

Is running for me so far, waiting...

**Comment by riverar** [comment]
Looks good using dotnet x64 SDK.

![image](https://user-images.githubusercontent.com/475132/197947705-5a40b33e-4f73-4ae7-bfda-0470a5b31a50.png)

**Comment by timsneath** [comment]
Thank you! That didn't work at first, but then I found a breadcrumb in your Clangsharp bug. After running:

```cmd
dotnet tool update -g ClangSharpPInvokeGenerator
```

which brought me from 14.x to 15.0.1, I was able to run successfully.

**Comment by tannergooding** [comment]
Sorry, missed this initially since `microsoft/*` repos don't show up in my notifications without additional sign-in.

This is a bit of a problem with `tool` packages in general in that there isn't really a good way to provide per `RID` versions when there are native dependencies. I'll have to look at manually packaging the NuGet such that it contains at least 7 different native DLLs (Windows x86, x64, Arm64; Linux x64, Arm64; MacOS x64, Arm64) and will correctly resolve them as an intermediate workaround.

Ideally the .NET Tools packages would have a way to handle this in the future so that things can work more smoothly and can work with AOT/Trimmed binaries as well.

**Comment by mikebattista** [comment]
Thanks Tanner. Assigning to you for now.

**Comment by mikebattista** [comment]
@tannergooding should I create a new issue for this in your repo?

**Comment by tannergooding** [comment]
That'd be ideal, thanks!

**Comment by riverar** [comment]
Closing this for now as it's just cluttering up the repo, is low value, and there's nothing to work on until dotnet documents [how the tooling works on arm64](https://github.com/dotnet/sdk/issues/28550) and/or addresses packaging ecosystem [issues](https://github.com/microsoft/win32metadata/issues/1305#issuecomment-1295303952).
