### ISSUE TITLE
WinmdGenerator: The "ScanLibs" task failed unexpectedly

### ISSUE THREAD

**Issue by riverar** [microsoft/win32metadata#591]
1. dotnet build /bl
2. (open msbuild.binlog)

```
The "ScanLibs" task failed unexpectedly.
System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime, Version=4.2.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
File name: 'System.Runtime, Version=4.2.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at MetadataTasks.ScanLibs.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()
```

That version of System.Runtime doesn't exist on nuget and the `dotnet build` entrypoint isn't manifested to redirect that assembly.

**Comment by riverar** [comment]
@wravery Hey Bill, noticed you recently checked in a webview2 generator sample. Any tips on running it? Is there an invocation incantation I'm missing?

**Comment by wravery** [comment]
IIRC, after building the rest of the win32metadata project with `DoAll.ps1`, I had to add a property to the command line build in the WebView2 sample directory pointing it at the binaries I just built instead of the NuGet for the SDK. The latest public NuGet at that time did not have support for the attribute I was adding.

**Comment by wravery** [comment]
I think it was the `Win32WinmdBinDir` property I needed to set.

**Comment by riverar** [comment]
@wravery Thanks a bunch, will explore that.

**Comment by riverar** [comment]
@sotteson1 Do you have a sample that demonstrates usage of this nuget outside the source tree?

**Comment by sotteson1** [comment]
I tried copying the files out of win32metadata\sources\msbuild\GeneratorSample into a directory outside the tree, then tried "dotnet build" and it worked. If that still fails for you, maybe you can build with verbose logging to give us more information about what's failing.

**Comment by riverar** [comment]
@sotteson1 Hmmm. Where is `$(PkgMicrosoft_ProjectReunion_DWrite)` defined? It's blank for me, so the build actually takes a very long time to fail because it's scanning my entire disk. Seems to indicate there are some implicit dependencies in play here.

Here's my repro repo:

1. `git clone https://github.com/riverar/repro-14f58e99d1ed`
2. `cd repro-14f58e99d1ed`
3. `dotnet build`

```
C:\Sources\repro-14f58e99d1ed [master ≡ +1 ~0 -0 !]> dotnet build /bl
Microsoft (R) Build Engine version 16.10.2+857e5a733 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

C:\Program Files\dotnet\sdk\5.0.302\MSBuild.dll -consoleloggerparameters:Summary -maxcpucount -restore -verbosity:m /bl .\sample.proj
  Determining projects to restore...
  All projects are up-to-date for restore.
  sample ->
C:\Users\Rafael.WITHIN\.nuget\packages\microsoft.windows.winmdgenerator\0.2.118-preview\Sdk\Sdk.targets(18,9): error MSB4018: The "ScanLibs" task failed unexpectedly. [C:\Sources\repro-14f58e99d1ed\sample.proj]
C:\Users\Rafael.WITHIN\.nuget\packages\microsoft.windows.winmdgenerator\0.2.118-preview\Sdk\Sdk.targets(18,9): error MSB4018: System.NullReferenceException: Object reference not set to an instance of an object. [C:\Sources\repro-14f58e99d1ed\sample.proj]
C:\Users\Rafael.WITHIN\.nuget\packages\microsoft.windows.winmdgenerator\0.2.118-preview\Sdk\Sdk.targets(18,9): error MSB4018:    at MetadataTasks.ScanLibs.GetLibs() [C:\Sources\repro-14f58e99d1ed\sample.proj]
C:\Users\Rafael.WITHIN\.nuget\packages\microsoft.windows.winmdgenerator\0.2.118-preview\Sdk\Sdk.targets(18,9): error MSB4018:    at MetadataTasks.ScanLibs.Execute() [C:\Sources\repro-14f58e99d1ed\sample.proj]
C:\Users\Rafael.WITHIN\.nuget\packages\microsoft.windows.winmdgenerator\0.2.118-preview\Sdk\Sdk.targets(18,9): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute() [C:\Sources\repro-14f58e99d1ed\sample.proj]
C:\Users\Rafael.WITHIN\.nuget\packages\microsoft.windows.winmdgenerator\0.2.118-preview\Sdk\Sdk.targets(18,9): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(ITaskExecutionHost taskExecutionHost, TaskLoggingContext taskLoggingContext, TaskHost taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask) [C:\Sources\repro-14f58e99d1ed\sample.proj]

Build FAILED.

C:\Users\Rafael.WITHIN\.nuget\packages\microsoft.windows.winmdgenerator\0.2.118-preview\Sdk\Sdk.targets(18,9): error MSB4018: The "ScanLibs" task failed unexpectedly. [C:\Sources\repro-14f58e99d1ed\sample.proj]
C:\Users\Rafael.WITHIN\.nuget\packages\microsoft.windows.winmdgenerator\0.2.118-preview\Sdk\Sdk.targets(18,9): error MSB4018: System.NullReferenceException: Object reference not set to an instance of an object. [C:\Sources\repro-14f58e99d1ed\sample.proj]
C:\Users\Rafael.WITHIN\.nuget\packages\microsoft.windows.winmdgenerator\0.2.118-preview\Sdk\Sdk.targets(18,9): error MSB4018:    at MetadataTasks.ScanLibs.GetLibs() [C:\Sources\repro-14f58e99d1ed\sample.proj]
C:\Users\Rafael.WITHIN\.nuget\packages\microsoft.windows.winmdgenerator\0.2.118-preview\Sdk\Sdk.targets(18,9): error MSB4018:    at MetadataTasks.ScanLibs.Execute() [C:\Sources\repro-14f58e99d1ed\sample.proj]
C:\Users\Rafael.WITHIN\.nuget\packages\microsoft.windows.winmdgenerator\0.2.118-preview\Sdk\Sdk.targets(18,9): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute() [C:\Sources\repro-14f58e99d1ed\sample.proj]
C:\Users\Rafael.WITHIN\.nuget\packages\microsoft.windows.winmdgenerator\0.2.118-preview\Sdk\Sdk.targets(18,9): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(ITaskExecutionHost taskExecutionHost, TaskLoggingContext taskLoggingContext, TaskHost taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask) [C:\Sources\repro-14f58e99d1ed\sample.proj]
    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:01.70
```

The msbuild.binlog generated via `/bl` shows:

```
C:\Users\Rafael.WITHIN\.nuget\packages\microsoft.windows.winmdgenerator\0.2.118-preview\Sdk\Sdk.targets(18,9): error MSB4018: The "ScanLibs" task failed unexpectedly.
System.NullReferenceException: Object reference not set to an instance of an object.
   at MetadataTasks.ScanLibs.GetLibs()
   at MetadataTasks.ScanLibs.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(ITaskExecutionHost taskExecutionHost, TaskLoggingContext taskLoggingContext, TaskHost taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask) [C:\Sources\repro-14f58e99d1ed\sample.proj]
```

**Comment by riverar** [comment]
@sotteson1 Oops, I think I cut too much from my repro. One moment.

**Comment by sotteson1** [comment]
PkgMicrosoft_ProjectReunion_DWrite should get set by the Microsoft.ProjectReunion.DWrite package brought in by: <PackageReference Include="Microsoft.ProjectReunion.DWrite" Version="0.5.6" GeneratePathProperty="true"/>

**Comment by riverar** [comment]
Dragged the folder to a fresh VM, installed latest .NET 5.0 SDK bits, issued a `dotnet build /bl` and:

```
C:\Users\Rafael\.nuget\packages\microsoft.windows.winmdgenerator\0.2.118-preview\Sdk\Sdk.targets(26,9): error MSB4018: The "ScrapeHeaders" task failed unexpectedly. [C:\Users\Rafael\desktop\generator\GeneratorSample.proj]
C:\Users\Rafael\.nuget\packages\microsoft.windows.winmdgenerator\0.2.118-preview\Sdk\Sdk.targets(26,9): error MSB4018: System.NullReferenceException: Object reference not set to an instance of an object. [C:\Users\Rafael\desktop\generator\GeneratorSample.proj]
C:\Users\Rafael\.nuget\packages\microsoft.windows.winmdgenerator\0.2.118-preview\Sdk\Sdk.targets(26,9): error MSB4018:    at MetadataTasks.ScrapeHeaders.ProcessPartitionItem(ITaskItem partitionItem) [C:\Users\Rafael\desktop\generator\GeneratorSample.proj]
C:\Users\Rafael\.nuget\packages\microsoft.windows.winmdgenerator\0.2.118-preview\Sdk\Sdk.targets(26,9): error MSB4018:    at MetadataTasks.ScrapeHeaders.Execute() [C:\Users\Rafael\desktop\generator\GeneratorSample.proj]
C:\Users\Rafael\.nuget\packages\microsoft.windows.winmdgenerator\0.2.118-preview\Sdk\Sdk.targets(26,9): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute() [C:\Users\Rafael\desktop\generator\GeneratorSample.proj]
C:\Users\Rafael\.nuget\packages\microsoft.windows.winmdgenerator\0.2.118-preview\Sdk\Sdk.targets(26,9): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(ITaskExecutionHost taskExecutionHost, TaskLoggingContext taskLoggingContext, TaskHost taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask) [C:\Users\Rafael\desktop\generator\GeneratorSample.proj]
```

Binlog attached.
[msbuild_binlog.zip](https://github.com/microsoft/win32metadata/files/6904515/msbuild_binlog.zip)

I'll pull out the debugger tonight and take a closer look. It seems to behave differently across multiple machines, which I'm sure is frustrating for both of us.

**Comment by sotteson1** [comment]
Thanks for checking it out with a debugger. Even getting a stack trace would be terrific.

**Comment by riverar** [comment]
Spent a bit of time with this and have concluded this issue is invalid. 😂 Was able to create a custom project, will PR some minor things in a moment.
